#!/bin/bash
set -e

function install_compose_check_arguments {
  if [ -z "${DOCKER_COMPOSE_VERSION}" ]; then
    echo "Missing env variable DOCKER_COMPOSE_VERSION" >&2
    exit 1
  fi
}

function install_compose_main {
  echo "Installing compose"
  sudo rm -f /usr/local/bin/docker-compose
  curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  chmod +x docker-compose
  sudo mv docker-compose /usr/local/bin
  docker-compose -v
}

if [ "$BASH_SOURCE" = "$0" ]; then
  deploy_to_rancher_main "$@"
fi
