#!/bin/bash
URL='https://s3-eu-west-1.amazonaws.com/boton-scripts/travis-helpers/v1.4.0/travis-helpers'
mkdir -p /tmp/bin
curl -L $URL > /tmp/bin/travis-helpers
chmod a+x /tmp/bin/travis-helpers
echo 'export PATH=$PATH:/tmp/bin'
