#!/bin/bash
URL=$(  curl -s https://api.github.com/repos/nico-acidtango/travis-helpers/releases/latest | \
        grep browser_download_url | cut -d '"' -f 4 | grep 'travis-helpers$' )
mkdir -p /tmp/bin
curl -L $URL > /tmp/bin/travis-helpers
chmod a+x /tmp/bin/travis-helpers
echo 'export PATH=$PATH:/tmp/bin'
