#!/bin/bash
function print_help {
  cat <<HELP
$0 COMMAND <options>

COMMANDS
  deploy
  push
  install-compose

HELP
}

function source_helpers {
  for file in $(dirname $0)/helpers/*; do
    source $file
  done
}

if [ "$#" -eq 0 ]; then
  print_help
  exit 0
fi

source_helpers

while (( "$#" )); do
  case "$1" in
    deploy) shift; deploy_to_rancher_main "$@";;
    push) shift; push_docker_image_main "$@";;
    install-compose) shift; install_compose_main "$@";;
    *) echo "Unknown command $1" >&2
  esac
  shift
done
