#!/bin/bash
function print_help {
  cat <<HELP
$0 <OPTIONS> COMMAND <options>

COMMANDS
  deploy
  push
  install
  install-compose
  prepare-docker

OPTIONS
  -P            only apply if is not pull request
  -M            only apply if it is master branch
  -b <branch>   only apply if it is given branch

HELP
}

function source_helpers {
  for file in $(dirname $0)/helpers/*; do
    source $file
  done
}

function check_pull_request {
  if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
    exit 0
  fi
}

function check_branch {
  if [ "$TRAVIS_BRANCH" != "$1" ]; then
    exit 0
  fi
}

function prepare_docker {
  installer_main compose $DOCKER_COMPOSE_VERSION
  installer_main awscli
  eval $(aws ecr get-login --no-include-email)
}

if [ "$#" -eq 0 ]; then
  print_help
  exit 0
fi

source_helpers

while (( "$#" )); do
  case "$1" in
    deploy) shift; deploy_to_rancher_main "$@"; exit $?;;
    push) shift; push_docker_image_main "$@"; exit $?;;
    install-compose) shift; installer_main compose "$@"; exit $?;;
    install) shift; installer_main "$@"; exit $?;;
    prepare-docker) shift; prepare_docker "$@"; exit $?;;
    -P) check_pull_request;;
    -M) check_branch master;;
    -b) shift; check_branch $1;;
    *) echo "Unknown command $1" >&2
  esac
  shift
done
